name: .NET Builds

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)

          # Build everything
          dotnet restore
          dotnet publish -r win-x64 --sc -c Release -o "build/win/"
          dotnet publish -r linux-x64 --sc -c Release -o "build/nix/"
          dotnet publish -r osx-x64 --sc -c Release -o "build/osx/"

          # Move files to same dir
          mkdir dist
          mv ./build/win/PyStubber.exe dist/PyStubber-$tag-win64.exe
          mv ./build/nix/PyStubber dist/PyStubber-$tag-linux64
          mv ./build/osx/PyStubber dist/PyStubber-$tag-osx64

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/PyStubber*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
